# Generated by Django 4.2.3 on 2023-12-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
