# Generated by Django 5.0 on 2023-12-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cumulative_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
